site_name: Fundamentals of Power BI
site_url: https://darthyody.github.io/powerbi/
theme:
   name: null
   custom_dir: 'cinder'
extra_css: [style.css]
markdown_extensions:
   # - codehilite(linenums=true)
   - admonition
   - attr_list
   - footnotes
   - meta
   - markdown_include.include
   - toc:
      permalink: True
   # - pymdownx.arithmatex
   # - pymdownx.betterem(smart_enable=all)
   # - pymdownx.caret
   # - pymdownx.critic
   - pymdownx.details
   - pymdownx.emoji:
         emoji_generator: !!python/name:pymdownx.emoji.to_svg
   # - pymdownx.inlinehilite
   # - pymdownx.magiclink
   # - pymdownx.markdown_include
   # - pymdownx.mark
   - pymdownx.smartsymbols
   - pymdownx.superfences
   # - pymdownx.tasklist(custom_checkbox=true)
   # - pymdownx.tilde
plugins:
   - replace
nav:
   - Welcome: index.md
   - 1. Introduction:
      - Overview: 1-Overview/overview.md
      - Table of Contents: 1-Overview/table-of-contents.md
      - Course Outline: 1-Overview/course-outline.md
   # - 2. Topics:
   #    - "Getting Started": 2-Topics/01-Getting-Started/01-What-is-Power-BI.md
   - 2. Course: 
      - "Part 1: Course Introduction":
         - "Welcome & Course Overview": 2-Course/01
         - "Introduction to Power BI: History & Overview": 2-Course/02
         - "Lab: End-to-end Introduction to Power BI Desktop": 2-Course/02lab
         - "Power BI Web & Mobile": 2-Course/10
         - "Lab: Using Power BI Web and Mobile": 2-Course/10lab
      - "Part 2: Getting Data into Power BI":
         - "Getting Data into Power Query": 2-Course/03
         - "Lab: Practice Connecting to Data Sources": 2-Course/03
         - "Modeling Data with Power Pivot": 2-Course/05
         - "Lab: Effective Data Modeling": 2-Course/05
      - "Part 3: Formatting Data":
         - "Making Powerful Data Transformations": 2-Course/04
         - "Lab: Using Power Query": 2-Course/04
         - "Introduction to R in Power BI": 2-Course/09
         - "Lab: Using R to create Visuals": 2-Course/09
         - "Introduction to DAX": 2-Course/13
         - "Lab: Using DAX in Power BI": 2-Course/13
         - "Overview of DAX Functions": 2-Course/14
         - "Lab: Practice Using DAX": 2-Course/14
      - "Part 4: Visualizing Data":
         - "Introduction to Visualizations": 2-Course/06
         - "Lab: Practicing with Simple Graphs": 2-Course/06
         - "Making Easy-to-Read Visuals": 2-Course/07
         - "Lab: Making Clear Visuals": 2-Course/07
         - "Reports & Dashboards": 2-Course/08
         - "Lab: Create Your Own Dashboards & Reports": 2-Course/08
      -  "Part 5: Additional Topics":
         - "Power Add-Ins": 2-Course/12
         - "Lab: Using Excel Add-Ins": 2-Course/12
         - "Exploring Data & Other Helpful Features": 2-Course/11
         - "Lab: Practice Using Additional Features": 2-Course/11
   # - 2. Course:
   #    - Monday:
   #       - "1 Welcome": 2-Course/01.md
   #       - "2 Power BI Fundamentals": 2-Course/02.md
   #       - "3 Getting Data into Power Query": 2-Course/03.md
   #       - "4 Making Powerful Data Transformations": 2-Course/04.md
   #    - Tuesday:
   #       - "5 Modeling Data with Power Pivot": 2-Course/05.md
   #       - "6 Introduction to Visualizations": 2-Course/06.md
   #       - "7 Making Easy-to-Read Visuals": 2-Course/07.md
   #       - "8 Reports & Dashboards": 2-Course/08.md
   #    - Wednesday:
   #       - "9 Introduction to R in Power BI": 2-Course/09.md
   #       - "10 Using R to create Visuals": 2-Course/10.md
   #       - "11 Exploring Data & Other Helpful Features": 2-Course/11.md
   #       - "12 Power Add-Ins": 2-Course/12.md
   #    - Thursday:
   #       - "13 Introduction to DAX": 2-Course/13.md
   #       - "14 Overview of DAX Functions": 2-Course/14.md
   #       - "15 Course Review": 2-Course/15.md
   #       - "16 Feedback & Graduation": 2-Course/16.md
   - 3. Appendix:
      - FAQ: 3-Appendix/FAQ.md